/**
 * @param {import("knex").Knex} knex
 */
export async function seed(knex) {
  await knex('cart_item').del();
  await knex('booking_item').del();
  await knex('booking').del();
  await knex('cart').del();
  await knex('account').del();
  await knex('event').del();

  await knex("event").insert([
    {
      title: "Copenhagen Coffee Crawl",
      venue: "Copenhagen Coffee Society",
      starts_at: "2026-06-23 18:30:00",
      description:
        "A relaxed Saturday walk between 4 specialty cafés. Includes tasting notes, small pastry, and brewing styles.",
      price: 100,
      currency: "DKK",
      total_tickets: 50,
    },
    {
      title: "After-Work Board Games Night",
      venue: "Norrebro Game Lounge",
      starts_at: "2026-06-25 19:00:00",
      description:
        "Drop in with friends or come solo. We’ll teach quick games, set you up at a table, and keep the vibe cozy and social.",
      price: 150,
      currency: "DKK",
      total_tickets: 40,
    },
    {
      title: "Beginner Pasta Workshop",
      venue: "Frederiksberg Kitchen Studio",
      starts_at: "2026-06-27 17:30:00",
      description:
        "Hands-on workshop: mix dough, roll sheets, shape pasta, and finish with a simple sauce. You’ll leave with a small take-home pack.",
      price: 250,
      currency: "DKK",
      total_tickets: 24,
    },
    {
      title: "Sunday Park Run & Stretch",
      venue: "Fælledparken Main Gate",
      starts_at: "2026-06-28 09:00:00",
      description:
        "Easy-paced community run (5K-ish) followed bretching. All levels welcome—walkers included.",
      price: 0,
      currency: "DKK",
      total_tickets: 120,
    },
    {
      title: "Indie Film Screening: Short Nights",
      venue: "Vesterbro Micro Cinema",
      starts_at: "2026-07-01 20:15:00",
      description:
        "A curated set of local short films with a short Q&A after. Seats are limited—arrive early for the best spots.",
      price: 75,
      currency: "DKK",
      total_tickets: 60,
    },
    {
      title: "Photography Walk: City Lights",
      venue: "Nyhavn Canal Entrance",
      starts_at: "2026-07-03 21:00:00",
      description:
        "Evening photo walk focused on street scenes and reflections. Bring any camera—even a phone—and we’ll share tips on composition and exposure.",
      price: 180,
      currency: "DKK",
      total_tickets: 30,
    },
    {
      title: "Bread & Butter Tasting",
      venue: "Amager Bake Lab",
      starts_at: "2026-07-05 11:00:00",
      description:
        "Taste 6 breads and 5 butters (classic + flavored). Learn what makes a good crumb, crust, and fermentation—and why butter matters.",
      price: 120,
      currency: "DKK",
      total_tickets: 36,
    },
    {
      title: "Live Jazz Trio at the Loft",
      venue: "Christianshavn Loft Stage",
      starts_at: "2026-07-08 19:00:00",
      description:
        "An intimate set with modern standards and originals. Ticket includes a welcome drink; doors open 19:00.",
      price: 300,
      currency: "DKK",
      total_tickets: 80,
    },
    {
      title: "Sourdough Masterclass",
      venue: "Bakery School",
      starts_at: "2026-07-10 10:00:00",
      description: "Learn to bake sourdough from scratch.",
      price: 200,
      currency: "DKK",
      total_tickets: 20,
    },
    {
      title: "Yoga in the Park",
      venue: "Central Park",
      starts_at: "2026-07-12 08:00:00",
      description: "Morning yoga for all levels.",
      price: 50,
      currency: "DKK",
      total_tickets: 100,
    },
    {
      title: "Wine Tasting Evening",
      venue: "Vineyard Cellar",
      starts_at: "2026-07-14 18:00:00",
      description: "Sample 8 wines with a sommelier.",
      price: 350,
      currency: "DKK",
      total_tickets: 30,
    },
    {
      title: "Coding Bootcamp",
      venue: "Tech Hub",
      starts_at: "2026-07-16 09:00:00",
      description: "Intro to web development.",
      price: 500,
      currency: "DKK",
      total_tickets: 25,
    },
    {
      title: "Artisan Cheese Night",
      venue: "Cheese Cave",
      starts_at: "2026-07-18 19:00:00",
      description: "Taste and learn about cheeses.",
      price: 180,
      currency: "DKK",
      total_tickets: 40,
    },
    {
      title: "Open Mic Poetry",
      venue: "Literary Cafe",
      starts_at: "2026-07-20 20:00:00",
      description: "Share your poetry or listen in.",
      price: 60,
      currency: "DKK",
      total_tickets: 50,
    },
    {
      title: "Street Food Festival",
      venue: "City Square",
      starts_at: "2026-07-22 12:00:00",
      description: "Food trucks and live music.",
      price: 0,
      currency: "DKK",
      total_tickets: 500,
    },
    {
      title: "Photography Basics",
      venue: "Art Studio",
      starts_at: "2026-07-24 15:00:00",
      description: "Learn camera settings and composition.",
      price: 120,
      currency: "DKK",
      total_tickets: 18,
    },
    {
      title: "Craft Beer Tasting",
      venue: "Brewery Bar",
      starts_at: "2026-07-26 17:00:00",
      description: "Sample local craft beers.",
      price: 160,
      currency: "DKK",
      total_tickets: 35,
    },
    {
      title: "Salsa Dance Night",
      venue: "Dance Hall",
      starts_at: "2026-07-28 20:00:00",
      description: "Beginner salsa class and social.",
      price: 90,
      currency: "DKK",
      total_tickets: 60,
    },
    {
      title: "Pottery Workshop",
      venue: "Clay Studio",
      starts_at: "2026-07-30 14:00:00",
      description: "Make your own pottery piece.",
      price: 220,
      currency: "DKK",
      total_tickets: 15,
    },
    {
      title: "Board Game Marathon",
      venue: "Game Cafe",
      starts_at: "2026-08-01 10:00:00",
      description: "12 hours of board games.",
      price: 80,
      currency: "DKK",
      total_tickets: 70,
    },
    {
      title: "Vegan Cooking Demo",
      venue: "Green Kitchen",
      starts_at: "2026-08-03 18:00:00",
      description: "Plant-based recipes and tasting.",
      price: 130,
      currency: "DKK",
      total_tickets: 28,
    },
    {
      title: "Film Quiz Night",
      venue: "Cinema Bar",
      starts_at: "2026-08-05 19:30:00",
      description: "Test your movie knowledge.",
      price: 60,
      currency: "DKK",
      total_tickets: 45,
    },
    {
      title: "Jazz Brunch",
      venue: "Rie",
      starts_at: "2026-08-07 11:00:00",
      description: "Live jazz and brunch buffet.",
      price: 210,
      currency: "DKK",
      total_tickets: 32,
    },
    {
      title: "Coding for Kids",
      venue: "Library Lab",
      starts_at: "2026-08-09 13:00:00",
      description: "Fun intro to coding for ages 8-12.",
      price: 70,
      currency: "DKK",
      total_tickets: 20,
    },
    {
      title: "Summer Book Swap",
      venue: "Community Center",
      starts_at: "2026-08-11 16:00:00",
      description: "Bring a book, take a book.",
      price: 0,
      currency: "DKK",
      total_tickets: 80,
    },
    {
      title: "Night Market",
      venue: "Old Town",
      starts_at: "2026-08-13 18:00:00",
      description: "Vendors, food, and music.",
      price: 0,
      currency: "DKK",
      total_tickets: 200,
    },
    {
      title: "Trivia Challenge",
      venue: "Pub Quiz Hall",
      starts_at: "2026-08-15 20:00:00",
      description: "Team trivia with prizes.",
      price: 50,
      currency: "DKK",
      total_tickets: 60,
    },
    {
      title: "Painting & Wine",
      venue: "Art Loft",
      starts_at: "2026-08-17 18:30:00",
      description: "Paint and sip event.",
      price: 180,
      currency: "DKK",
      total_tickets: 22,
    },
    {
      title: "Sunday Farmers Market",
      venue: "Market Square",
      starts_at: "2026-08-19 09:00:00",
      description: "Fresh produce and local goods.",
      price: 0,
      currency: "DKK",
      total_tickets: 300,
    },
    {
      title: "Chess Tournament",
      venue: "Chess Club",
      starts_at: "2026-08-21 10:00:00",
      description: "Open chess tournament.",
      price: 100,
      currency: "DKK",
      total_tickets: 40,
    },
    {
      title: "Karaoke Night",
      venue: "Music Bar",
      starts_at: "2026-08-23 21:00:00",
      description: "Sing your favorite hits.",
      price: 70,
      currency: "DKK",
      total_tickets: 55,
    },
    {
      title: "Baking for Beginners",
      venue: "Bakery School",
      starts_at: "2026-08-25 15:00:00",
      description: "Learn to bake cakes and cookies.",
      price: 110,
      currency: "DKK",
      total_tickets: 18,
    },
  ]);
}
